### ISSUE TITLE
OpenSSL Error - bignum.h: In constructor ‘CBigNum::CBigNum()’: 

### ISSUE THREAD

**Issue by toptim** [fanaticoscriptosoficial/Fanaticos_Cash#1]
alert.cpp:60:9: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         "    nExpiration  = %"PRId64"\n"
         ^
In file included from key.h:15:0,
                 from alert.cpp:12:
bignum.h:57:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:19:0,
                 from bignum.h:13,
                 from key.h:15,
                 from alert.cpp:12:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from key.h:15:0,
                 from alert.cpp:12:
bignum.h: In constructor ‘CBigNum::CBigNum()’:
bignum.h:62:9: error: ‘BN_init’ was not declared in this scope

**Comment by LightBurdenOfficial** [comment]
> alert.cpp:60:9: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
> " nExpiration = %"PRId64"\n"
> ^
> In file included from key.h:15:0,
> from alert.cpp:12:
> bignum.h:57:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
> class CBigNum : public BIGNUM
> ^~~~~~
> In file included from /usr/include/openssl/bn.h:19:0,
> from bignum.h:13,
> from key.h:15,
> from alert.cpp:12:
> /usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
> typedef struct bignum_st BIGNUM;
> ^~~~~~~~~
> In file included from key.h:15:0,
> from alert.cpp:12:
> bignum.h: In constructor ‘CBigNum::CBigNum()’:
> bignum.h:62:9: error: ‘BN_init’ was not declared in this scope


wget http://www.openssl.org/source/openssl-1.0.2a.tar.gz
tar -xvzf openssl-1.0.2a.tar.gz
cd openssl-1.0.2a
./config --prefix=/usr/
make
sudo make install
